Task/04 react router
max-underthesun/react-shop pull request #5
Opened 2018-12-16 15:07 UTC by max-underthesun

2018-12-20 06:45 UTC, max-underthesun commented on webpack.config.js
> +    contentBase: path.join(__dirname, '/'),
решил вместо перемещения `index.html` в `public` поменять `contentBase`

2018-12-20 07:42 UTC, index01d requested changes

2018-12-20 07:42 UTC, index01d commented on webpack.config.js
> +    contentBase: path.join(__dirname, '/'),
дело прямо скажем небезопасное

2018-12-20 07:42 UTC, index01d commented on src/App.js
> +      <contextCart.Provider value={{ cart, addProduct: this.addProduct }}>
нужно вынести состояние корзины и настройку контекста в CartContainer и обернуть этим контейнером приложение

2018-12-20 07:42 UTC, index01d commented on src/App.js
> +      <contextCart.Provider value={{ cart, addProduct: this.addProduct }}>
чтобы не перемешивать код инициализации роутера и работу с корзиной

2018-12-25 12:10 UTC, index01d approved these changes

2019-01-06 13:54 UTC, merged